name: 投稿新星
description: 如果你觉得这个玩家形象很特殊值得收录，请告诉我们
labels: ["名人"]
body:
  - type: dropdown
    id: "yml-1"
    attributes:
      label: "名人形象"
      description: "请选择名人的形象（选择后根据提示填写相关内容）"
      options:
        - 正面形象（例如突出贡献者）
        - 负面形象（惹人讨厌者，例如熊孩子）
    validations:
      required: true

  - type: checkboxes
    id: "yml-2"
    attributes:
      label: "确认同意（仅适用于正面形象）"
      description: "如果选择了正面形象，请确认是否已获得当事人的同意。（当你选择负面是这个可以不用填）"
      options:
        - label: "当事人已经同意"

  - type: textarea
    id: "yml-4"
    attributes:
      label: "经当事人同意"
      description: "如果选择了正面形象，请提供当事人的声明。"
      placeholder: "-（请在这里填写，没有请填无）-"
    validations:
      required: true

  - type: textarea
    id: "yml-3"
    attributes:
      label: "描述行为（仅适用于负面形象）"
      description: "如果选择了负面形象，请描述相关行为。"
      placeholder: "-（请在这里填写，没有请填无）-"
    validations:
      required: true

  - type: textarea
    id: "yml-5"
    attributes:
      label: "上传文件（仅适用于正面形象）"
      description: "如果选择了正面形象，请提供相关文件描述事件。"
      placeholder: "-（请在这里填写，没有请填无）-"
    validations:
      required: true

  - type: checkboxes
    id: "yml-6"
    attributes:
      label: "确认相关"
      description: "请确保与地球村相关。"
      options:
        - label: "是的！我确认该对象与地球村服务器相关，无关人员不收录。"
    validations:
      required: true

  - type: textarea
    id: "yml-7"
    attributes:
      label: "请提供聊天记录"
      placeholder: "-（请在这里上传）-"
    validations:
      required: true

  - type: textarea
    id: "yml-8"
    attributes:
      label: "请提供“名人”联系方式（专指负面形象）"
      placeholder: "-（微信，QQ，Github，B站主页）- （当然如果当事人同意，也可以留正面形象者联系方式）"
    validations:
      required: true

  - type: textarea
    id: "yml-9"
    attributes:
      label: "可以提供现成的markdown文档，但是要把文档内引用的图片文件一同打包"
      placeholder: "-（请在这里上传）-"
    validations:
      required: false
  - type: checkboxes
    id: "yml-2"
    attributes:
      label: "内容要求"
      description: "我确保内容属实且完整，文案保持中立，没有断章取义"
      options:
        - label: "是！"
