name: 功能请求
description: none
labels: ["功能请求"]
body:
  - type: checkboxes
    id: "yml-1"
    attributes:
      label: "名人形象"
      description: "请选择名人的形象（只能选择一项）。"
      options:
        - label: "正面形象"
          value: "zheng"
        - label: "负面形象"
          value: "fu"
      required: true
  - type: conditional
    id: "conditional-positive"
    condition: "yml-1 == 'zheng'"
    fields:
      - type: checkboxes
        id: "yml-2"
        attributes:
          label: "确认同意"
          description: "请确保经过当事人同意。"
          options:
            - label: "当事人已经同意"
              required: true
      - type: textarea
        id: "yml-4"
        attributes:
          label: 请提供当事人声明
          placeholder: "-（请在这里回答）-"
          required: true
  - type: conditional
    id: "conditional-negative"
    condition: "yml-1 == 'fu'"
    fields:
      - type: textarea
        id: "yml-3"
        attributes:
          label: 描述行为
          placeholder: "-（请在这里回答）-"
          required: true
      - type: textarea
        id: "yml-5"
        attributes:
          label: 上传文件（包括发生的事）"
          placeholder: "-（请在这里上传）-"
          required: true
